create extension if not exists pgcrypto;

create table if not exists public.fleet_users (
  id text primary key,
  name text not null,
  department text not null,
  role text not null,
  phone text,
  created_at timestamptz not null default now()
);

create table if not exists public.fleet_keys (
  id text primary key,
  vehicle text not null,
  key_id text not null unique,
  department text not null,
  custodian_id text not null references public.fleet_users(id),
  received_at timestamptz not null default now(),
  job_card_status text not null default 'open' check (job_card_status in ('open', 'closed')),
  vehicle_status text not null default 'inside_garage' check (vehicle_status in ('inside_garage', 'outside_garage')),
  transfer_status text not null default 'assigned' check (transfer_status in ('assigned', 'transfer_pending', 'missing')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.key_history (
  id bigint generated by default as identity primary key,
  key_id text not null references public.fleet_keys(id) on delete cascade,
  title text not null,
  detail text not null,
  occurred_at timestamptz not null default now(),
  tone text not null check (tone in ('blue', 'green', 'amber', 'red', 'gray'))
);

create table if not exists public.fleet_transfers (
  id text primary key,
  sender_id text not null references public.fleet_users(id),
  recipient_id text not null references public.fleet_users(id),
  purpose text not null check (purpose in ('Recovery', 'Repair', 'Parking')),
  kind text not null default 'single' check (kind in ('single', 'bulk')),
  status text not null default 'pending' check (status in ('pending', 'accepted', 'rejected', 'expired', 'cancelled')),
  started_at timestamptz not null default now(),
  expires_at timestamptz not null default (now() + interval '2 minutes'),
  resolved_at timestamptz,
  created_at timestamptz not null default now()
);

create table if not exists public.fleet_transfer_items (
  transfer_id text not null references public.fleet_transfers(id) on delete cascade,
  key_id text not null references public.fleet_keys(id),
  primary key (transfer_id, key_id)
);

create table if not exists public.driver_keys (
  id text primary key,
  vehicle text not null,
  key_id text not null unique,
  driver_id text references public.fleet_users(id),
  status text not null default 'available' check (status in ('available', 'allotted', 'missing', 'recovered')),
  allotted_at timestamptz,
  created_at timestamptz not null default now()
);

create table if not exists public.fleet_penalties (
  id text primary key,
  driver_key_id text not null references public.driver_keys(id),
  driver_id text not null references public.fleet_users(id),
  reason text not null check (reason in ('lost_key', 'not_found_at_vehicle_recovery')),
  amount numeric(12, 2) not null check (amount > 0),
  issued_at timestamptz not null default now(),
  status text not null default 'active' check (status in ('active', 'reverted')),
  reverted_at timestamptz
);

create index if not exists fleet_keys_custodian_idx on public.fleet_keys(custodian_id);
create index if not exists fleet_transfers_sender_idx on public.fleet_transfers(sender_id, started_at desc);
create index if not exists fleet_transfers_recipient_idx on public.fleet_transfers(recipient_id, started_at desc);
create index if not exists fleet_penalties_driver_idx on public.fleet_penalties(driver_id, issued_at desc);

create or replace view public.fleet_key_records as
select
  k.id,
  k.vehicle,
  k.key_id,
  k.department,
  k.custodian_id,
  u.name as custodian_name,
  k.received_at,
  k.job_card_status,
  k.vehicle_status,
  k.transfer_status,
  coalesce(
    (
      select jsonb_agg(
        jsonb_build_object(
          'title', h.title,
          'detail', h.detail,
          'occurredAt', h.occurred_at,
          'tone', h.tone
        ) order by h.occurred_at desc
      )
      from public.key_history h
      where h.key_id = k.id
    ),
    '[]'::jsonb
  ) as history
from public.fleet_keys k
join public.fleet_users u on u.id = k.custodian_id;

create or replace view public.fleet_transfer_records as
select
  t.id,
  coalesce(array_agg(i.key_id order by i.key_id) filter (where i.key_id is not null), '{}'::text[]) as key_ids,
  t.recipient_id,
  recipient.name as recipient_name,
  coalesce(string_agg(k.vehicle, ', ' order by k.vehicle), '') as vehicle,
  t.sender_id,
  sender.name as sender_name,
  t.purpose,
  t.started_at,
  t.expires_at,
  t.kind,
  t.status
from public.fleet_transfers t
join public.fleet_users sender on sender.id = t.sender_id
join public.fleet_users recipient on recipient.id = t.recipient_id
left join public.fleet_transfer_items i on i.transfer_id = t.id
left join public.fleet_keys k on k.id = i.key_id
group by t.id, recipient.name, sender.name;

create or replace view public.fleet_driver_key_records as
select
  d.id,
  d.vehicle,
  d.key_id,
  coalesce(d.driver_id, '') as driver_id,
  coalesce(u.name, '') as driver_name,
  coalesce(u.phone, '') as phone,
  d.status,
  d.allotted_at
from public.driver_keys d
left join public.fleet_users u on u.id = d.driver_id;

create or replace view public.fleet_penalty_records as
select
  p.id,
  p.driver_key_id,
  p.driver_id,
  u.name as driver_name,
  d.vehicle,
  d.key_id,
  p.reason,
  p.amount,
  p.issued_at,
  p.status,
  p.reverted_at
from public.fleet_penalties p
join public.fleet_users u on u.id = p.driver_id
join public.driver_keys d on d.id = p.driver_key_id;

create or replace view public.fleet_leaderboard as
select
  u.id as driver_id,
  u.name as driver_name,
  count(p.id) filter (where p.status = 'active')::int as active_penalties,
  greatest(0, 100 - (count(p.id) filter (where p.status = 'active') * 10)::int) as score,
  rank() over (
    order by greatest(0, 100 - (count(p.id) filter (where p.status = 'active') * 10)::int) desc, u.name
  )::int as rank
from public.fleet_users u
left join public.fleet_penalties p on p.driver_id = u.id
group by u.id, u.name;

create or replace function public.create_fleet_transfer(
  p_sender_id text,
  p_recipient_id text,
  p_key_ids text[],
  p_purpose text,
  p_kind text default 'single'
) returns jsonb language plpgsql security definer set search_path = public as $$
declare
  transfer_id text := 'transfer-' || replace(gen_random_uuid()::text, '-', '');
  key_count integer;
begin
  if coalesce(array_length(p_key_ids, 1), 0) = 0 then
    raise exception 'At least one key is required';
  end if;
  if p_sender_id = p_recipient_id then
    raise exception 'Sender and recipient must be different';
  end if;
  select count(*) into key_count
  from public.fleet_keys
  where id = any(p_key_ids)
    and custodian_id = p_sender_id
    and transfer_status = 'assigned';
  if key_count <> array_length(p_key_ids, 1) then
    raise exception 'Every key must be assigned to the sender and have no pending transfer';
  end if;

  insert into public.fleet_transfers (id, sender_id, recipient_id, purpose, kind)
  values (transfer_id, p_sender_id, p_recipient_id, p_purpose, p_kind);
  insert into public.fleet_transfer_items (transfer_id, key_id)
  select transfer_id, unnest(p_key_ids);
  update public.fleet_keys
  set transfer_status = 'transfer_pending', updated_at = now()
  where id = any(p_key_ids);
  insert into public.key_history (key_id, title, detail, tone)
  select id, 'Transfer initiated', p_sender_id || ' sent key to ' || p_recipient_id, 'amber'
  from public.fleet_keys where id = any(p_key_ids);
  return (select to_jsonb(v) from public.fleet_transfer_records v where v.id = transfer_id);
end;
$$;

create or replace function public.accept_fleet_transfer(
  p_transfer_id text,
  p_recipient_id text
) returns jsonb language plpgsql security definer set search_path = public as $$
declare
  transfer public.fleet_transfers;
begin
  select * into transfer from public.fleet_transfers where id = p_transfer_id for update;
  if not found then raise exception 'Transfer not found'; end if;
  if transfer.status <> 'pending' then raise exception 'Transfer is no longer pending'; end if;
  if transfer.recipient_id <> p_recipient_id then raise exception 'Only the recipient can accept this transfer'; end if;
  if transfer.expires_at <= now() then
    update public.fleet_transfers set status = 'expired', resolved_at = now() where id = p_transfer_id;
    update public.fleet_keys set transfer_status = 'assigned', updated_at = now()
    where id in (select key_id from public.fleet_transfer_items where transfer_id = p_transfer_id);
    raise exception 'Transfer has expired';
  end if;
  update public.fleet_transfers set status = 'accepted', resolved_at = now() where id = p_transfer_id;
  update public.fleet_keys
  set custodian_id = p_recipient_id, received_at = now(), transfer_status = 'assigned', updated_at = now()
  where id in (select key_id from public.fleet_transfer_items where transfer_id = p_transfer_id);
  insert into public.key_history (key_id, title, detail, tone)
  select i.key_id, 'Transfer accepted', 'Accepted by ' || p_recipient_id, 'green'
  from public.fleet_transfer_items i where i.transfer_id = p_transfer_id;
  return (select to_jsonb(v) from public.fleet_transfer_records v where v.id = p_transfer_id);
end;
$$;

create or replace function public.reject_fleet_transfer(
  p_transfer_id text,
  p_recipient_id text
) returns jsonb language plpgsql security definer set search_path = public as $$
declare
  transfer public.fleet_transfers;
begin
  select * into transfer from public.fleet_transfers where id = p_transfer_id for update;
  if not found then raise exception 'Transfer not found'; end if;
  if transfer.status <> 'pending' or transfer.recipient_id <> p_recipient_id then
    raise exception 'Only a pending transfer can be rejected by its recipient';
  end if;
  update public.fleet_transfers set status = 'rejected', resolved_at = now() where id = p_transfer_id;
  update public.fleet_keys set transfer_status = 'assigned', updated_at = now()
  where id in (select key_id from public.fleet_transfer_items where transfer_id = p_transfer_id);
  return (select to_jsonb(v) from public.fleet_transfer_records v where v.id = p_transfer_id);
end;
$$;

create or replace function public.cancel_fleet_transfer(
  p_transfer_id text,
  p_sender_id text
) returns jsonb language plpgsql security definer set search_path = public as $$
declare
  transfer public.fleet_transfers;
begin
  select * into transfer from public.fleet_transfers where id = p_transfer_id for update;
  if not found then raise exception 'Transfer not found'; end if;
  if transfer.status <> 'pending' or transfer.sender_id <> p_sender_id then
    raise exception 'Only the sender can cancel a pending transfer';
  end if;
  update public.fleet_transfers set status = 'cancelled', resolved_at = now() where id = p_transfer_id;
  update public.fleet_keys set transfer_status = 'assigned', updated_at = now()
  where id in (select key_id from public.fleet_transfer_items where transfer_id = p_transfer_id);
  return (select to_jsonb(v) from public.fleet_transfer_records v where v.id = p_transfer_id);
end;
$$;

create or replace function public.allot_driver_key(
  p_driver_key_id text,
  p_driver_id text,
  p_actor_id text
) returns jsonb language plpgsql security definer set search_path = public as $$
begin
  if not exists (select 1 from public.fleet_users where id = p_driver_id) then
    raise exception 'Driver not found';
  end if;
  update public.driver_keys
  set driver_id = p_driver_id, status = 'allotted', allotted_at = now()
  where id = p_driver_key_id and status in ('available', 'recovered');
  if not found then raise exception 'Driver key is not available for allotment'; end if;
  return (select to_jsonb(v) from public.fleet_driver_key_records v where v.id = p_driver_key_id);
end;
$$;

create or replace function public.issue_fleet_penalty(
  p_driver_key_id text,
  p_reason text,
  p_amount numeric,
  p_actor_id text
) returns jsonb language plpgsql security definer set search_path = public as $$
declare
  key_row public.driver_keys;
  penalty_id text := 'penalty-' || replace(gen_random_uuid()::text, '-', '');
begin
  select * into key_row from public.driver_keys where id = p_driver_key_id for update;
  if not found or key_row.status <> 'allotted' or key_row.driver_id is null then
    raise exception 'Only an allotted driver key can receive a penalty';
  end if;
  insert into public.fleet_penalties (id, driver_key_id, driver_id, reason, amount)
  values (penalty_id, p_driver_key_id, key_row.driver_id, p_reason, p_amount);
  update public.driver_keys set status = 'missing' where id = p_driver_key_id;
  return (select to_jsonb(v) from public.fleet_penalty_records v where v.id = penalty_id);
end;
$$;

create or replace function public.revert_fleet_penalty(
  p_penalty_id text,
  p_actor_id text
) returns jsonb language plpgsql security definer set search_path = public as $$
declare
  penalty public.fleet_penalties;
begin
  select * into penalty from public.fleet_penalties where id = p_penalty_id for update;
  if not found or penalty.status <> 'active' then raise exception 'Active penalty not found'; end if;
  update public.fleet_penalties set status = 'reverted', reverted_at = now() where id = p_penalty_id;
  update public.driver_keys set status = 'recovered' where id = penalty.driver_key_id;
  return (select to_jsonb(v) from public.fleet_penalty_records v where v.id = p_penalty_id);
end;
$$;

grant select on public.fleet_key_records, public.fleet_transfer_records,
  public.fleet_driver_key_records, public.fleet_penalty_records,
  public.fleet_leaderboard to anon, authenticated;
grant execute on function public.create_fleet_transfer(text, text, text[], text, text) to anon, authenticated;
grant execute on function public.accept_fleet_transfer(text, text) to anon, authenticated;
grant execute on function public.reject_fleet_transfer(text, text) to anon, authenticated;
grant execute on function public.cancel_fleet_transfer(text, text) to anon, authenticated;
grant execute on function public.allot_driver_key(text, text, text) to anon, authenticated;
grant execute on function public.issue_fleet_penalty(text, text, numeric, text) to anon, authenticated;
grant execute on function public.revert_fleet_penalty(text, text) to anon, authenticated;